# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_abt(object):
    def setupUi(self, abt):
        abt.setObjectName("abt")
        abt.resize(300, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pictures/img/fl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        abt.setWindowIcon(icon)
        abt.setAutoFillBackground(False)
        abt.setStyleSheet("")
        self.textBrowser = QtWidgets.QTextBrowser(abt)
        self.textBrowser.setGeometry(QtCore.QRect(40, 40, 211, 241))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setAutoFillBackground(True)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-width:0;\n"
"border-style:outset;")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(abt)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 400))
        self.label.setStyleSheet("image: url(:/pictures/img/aboutbg.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(abt)
        self.checkBox.setGeometry(QtCore.QRect(210, 370, 71, 16))
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);background:transparent")
        self.checkBox.setObjectName("checkBox")
        self.label.raise_()
        self.textBrowser.raise_()
        self.checkBox.raise_()

        self.retranslateUi(abt)
        QtCore.QMetaObject.connectSlotsByName(abt)

    def retranslateUi(self, abt):
        _translate = QtCore.QCoreApplication.translate
        abt.setWindowTitle(_translate("abt", "注册引导"))
        self.textBrowser.setHtml(_translate("abt", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600; color:#ffffff;\">注册须知：</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt; color:#ffffff;\">点击红色图标设置用户头像。用户名须由大写字母开头，可包含数字和字母，长度1-8位密码仅且必须包含字母和数字，长度6-12位。密保问题和答案可自定义设置。请务必保存好密保问题和答案，这是找回密码的唯一凭证</span></p></body></html>"))
        self.checkBox.setText(_translate("abt", "不再显示"))
import img_rc
